#!/usr/bin/env bash

# live-grep: interactive search, output is "file:line" pairs
FILE_PATHS=$(live-grep --exit-on-execution | tr '\n' ' ' | sed 's/ *$//')

# Get ID of the pane above in wezterm, which should be Helix
HELIX_PANE_ID=$(wezterm cli get-pane-direction Up)

if [[ -n "$FILE_PATHS" ]]; then

  # zellij action toggle-floating-panes
  # zellij action write-chars ":open $FILE_PATHS"
  # if wezterm --version &> /dev/null; then
  #   printf "\r" | wezterm cli send-text  --no-paste
  # fi
  # zellij action toggle-floating-panes
  # zellij action close-pane
  
  # Send ":" to start command input in Helix
  wezterm cli send-text --pane-id "$HELIX_PANE_ID" --no-paste ":"

  # Send the "open" command with file path(s) to the pane
  wezterm cli send-text --pane-id "$HELIX_PANE_ID" "open $FILE_PATHS"

  # Simulate 'Enter' key to execute the command
  printf "\r" | wezterm cli send-text --pane-id "$HELIX_PANE_ID" --no-paste
fi

