#!/usr/bin/env bash

HELIX_PANE_ID=$(wezterm cli get-pane-direction Up)

FILE_LINE=$(wezterm cli get-text --pane-id $HELIX_PANE_ID)
RES=$(echo $FILE_LINE | rg -e "(?:NOR|INS|SEL)\s+(\S*)\s[^│]* (\d+):*.*" -o --replace '$1 $2')
FILE=$(echo $RES | choose 0)
LINE=$(echo $RES | choose 1)

FILE=$(eval echo $FILE)
# live-grep: interactive search, output is "file:line" pairs
FILE_PATHS=$(nnn-pick $FILE | tr '\n' ' ' | sed 's/ *$//')

# Get ID of the pane above in wezterm, which should be Helix
HELIX_PANE_ID=$(wezterm cli get-pane-direction Left)
if [ -z "${HELIX_PANE_ID}" ]; then
  HELIX_PANE_ID=$(wezterm cli split-pane --up --percent 20)
fi


if [[ -n "$FILE_PATHS" ]]; then

  # zellij action toggle-floating-panes
  # zellij action write-chars ":open $FILE_PATHS"
  # if wezterm --version &> /dev/null; then
  #   printf "\r" | wezterm cli send-text  --no-paste
  # fi
  # zellij action toggle-floating-panes
  # zellij action close-pane

  wezterm cli send-text --pane-id "$HELIX_PANE_ID" --no-paste ":"

  # Send the "open" command with file path(s) to the pane
  wezterm cli send-text --pane-id "$HELIX_PANE_ID" "open $FILE_PATHS"

  # Simulate 'Enter' key to execute the command
  printf "\r" | wezterm cli send-text --pane-id "$HELIX_PANE_ID" --no-paste

fi
